---
- name: Install Bind
  ansible.builtin.dnf:
    name: " {{ item }}"
    state: present
    update_cache: true
  loop:
    - bind
    - bind-utils

- name: Open Firewall Ports for Bind
  ansible.posix.firewalld:
    port: " {{ item }}"
    permanent: true
    state: enabled
    immediate: true
  loop:
    - 53/tcp
    - 53/udp